### ISSUE TITLE
Learn github ticketing system (Issues/Milestones)

### ISSUE THREAD

**Issue by vstepona** [vstepona/Locate_func#2]
Be an ACE in git by the end of today bro!!!

**Comment by vstepona** [comment]
comment 1

**Comment by KevinWhalen** [comment]
Learned the [issue tracking](https://github.com/vstepona/Locate_func/issues) system, how to create [milestones](https://github.com/vstepona/Locate_func/issues/milestones), and add issues to milestones.

**Comment by vstepona** [comment]
Updates in [references](https://github.com/vstepona/Locate_func/blob/master/Documentation/references.md)  file.
