### ISSUE TITLE
create schedule

### ISSUE THREAD

**Issue by vstepona** [vstepona/Locate_func#4]
create rough schedule for 2 months

**Comment by vstepona** [comment]
I am working on this

**Comment by vstepona** [comment]
I am done for now

**Comment by KevinWhalen** [comment]
Schedule will be for the next two months with [milestones](https://github.com/vstepona/Locate_func/issues/milestones) set for every week.

**Comment by KevinWhalen** [comment]
Create a [milestone](https://github.com/vstepona/Locate_func/issues/milestones) for every week and assign high level issues/goals to them. Milestones names can be generic at first, but then have their name and descriptions updated as more specific issues get created for them.

**Comment by vstepona** [comment]
Rough Schedule was created. Will edit/update as we go.
