### ISSUE TITLE
create Eclipse plugin project template

### ISSUE THREAD

**Issue by vstepona** [vstepona/Locate_func#6]
Choose and create Eclipse plugin project template

**Comment by KevinWhalen** [comment]
Links about creating an Eclipse Plug-in:
- [Plugin Development Environment](http://www.eclipse.org/articles/Article-PDE-does-plugins/PDE-intro.html)
- [Creating a plugin - Help Site](http://help.eclipse.org/kepler/index.jsp?topic=%2Forg.eclipse.rse.doc.isv%2Fguide%2Ftutorial%2FpdeProject.html)
- [Eclipse PlugIn Article](http://www.vogella.com/tutorials/EclipsePlugIn/article.html)

The [Eclipse Help Site](http://help.eclipse.org/kepler/index.jsp) has API references.

**Comment by vstepona** [comment]
Plugin template needs research. Use links above.

**Comment by vstepona** [comment]
scrap plug in, not relevant to the project
